### ISSUE TITLE
Add GraphQL API to fetch resources from the client-side.

### ISSUE THREAD

**Issue by ohpyupi** [jyon124/DogCEO#18]
### Description
Currently, the client-side application directly calls the external API. Instead, we will install a [GraphQL](
https://graphql.org/) API layer so that it will provide an interface for the client application to fetch resources.

### Open Questions
- What would be the server-side programming language? Node or Ruby?
- What library to be used for the GraphQL API interface.
  - [Apollo Server](https://www.apollographql.com/docs/apollo-server/getting-started/) - NodeJS
  - [GraphQL Ruby](https://graphql-ruby.org/) - Ruby
  - etc.
- What library to be used in the client application to communicate with the GraphQL API interface.
  - [Apollo Client](https://www.apollographql.com/docs/react/)

**Comment by jyon124** [comment]
- **What would be the server-side programming language? Node or Ruby?**
In my opinion, in-demand jobs, Node's number of job opportunities is higher than Ruby, so I believe that Node is better for the server-side programming language.

- **What library to be used for the GraphQL API interface.
Apollo Server - NodeJS
GraphQL Ruby - Ruby
etc.**
Since I've chosen Node, Apollo Server is better because it works well with Node.

- **What library to be used in the client application to communicate with the GraphQL API interface.
Apollo Client**
Apollo Client is the right choice since it is designed to work well with the React used for building the DogCEO application.
